/**
 * Sync Thronos deployment environment to roadway-assistant.
 * 
 * Usage:
 *   npx tsx scripts/sync-thronos-env.ts
 * 
 * This script:
 * 1. Reads from Thronos deployment (local or Railway)
 * 2. Extracts contract addresses and chain config
 * 3. Generates roadway-assistant .env.thronos with synced values
 * 4. Optionally updates Railway service variables
 */

import * as fs from 'fs';
import * as path from 'path';
import { execSync } from 'child_process';

interface ThronosConfig {
  nodeUrl: string;
  chainId: string | number;
  evmRpcUrl: string;
  deployerKey: string;
  platformKey: string;
  platformWallet: string;
  escrowContract: string;
  servicebookContract: string;
  rewardVaultContract: string;
  rewardTokenAddress: string;
  attestationApiKey: string;
}

const THRONOS_ROOT = path.resolve(process.cwd(), '../../thronos-v3.6');
const ROADWAY_ROOT = process.cwd();

/**
 * Read Thronos .env file and extract deployment values.
 */
function readThronosEnv(): Partial<ThronosConfig> {
  const envPath = path.join(THRONOS_ROOT, '.env');
  
  if (!fs.existsSync(envPath)) {
    console.error(`❌ Thronos .env not found at: ${envPath}`);
    console.error(`   Please ensure thronos-v3.6 is cloned at: ${THRONOS_ROOT}`);
    process.exit(1);
  }

  const content = fs.readFileSync(envPath, 'utf-8');
  const env: Record<string, string> = {};
  
  content.split('\n').forEach(line => {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) return;
    const [key, value] = trimmed.split('=');
    if (key && value) {
      env[key.trim()] = value.trim().replace(/^["']|["']$/g, '');
    }
  });

  return {
    nodeUrl: env.MASTER_URL || env.THRONOS_NODE_URL || 'https://thronos-core.up.railway.app',
    chainId: env.THRONOS_CHAIN_ID || '1337',
    evmRpcUrl: env.THRONOS_EVM_RPC_URL || 'http://localhost:8545',
  };
}

/**
 * Read deployment output JSON (generated by `npm run chain:deploy:thronos`).
 */
function readDeploymentOutput(): Partial<ThronosConfig> {
  const deployPath = path.join(THRONOS_ROOT, 'deployment.json');
  
  if (!fs.existsSync(deployPath)) {
    console.warn(`⚠️  Deployment output not found at: ${deployPath}`);
    console.warn(`   Run: cd ${THRONOS_ROOT} && npm run chain:deploy:thronos`);
    return {};
  }

  try {
    const deploy = JSON.parse(fs.readFileSync(deployPath, 'utf-8'));
    return {
      escrowContract: deploy.escrow?.address || deploy.ESCROW_CONTRACT,
      servicebookContract: deploy.servicebook?.address || deploy.SERVICEBOOK_CONTRACT,
      rewardVaultContract: deploy.rewardVault?.address || deploy.REWARD_VAULT_CONTRACT,
      rewardTokenAddress: deploy.rewardToken?.address || deploy.REWARD_TOKEN_ADDRESS,
      deployerKey: deploy.deployer?.privateKey || process.env.THRONOS_DEPLOYER_PRIVATE_KEY,
      platformKey: deploy.platform?.privateKey || process.env.THRONOS_PLATFORM_PRIVATE_KEY,
      platformWallet: deploy.platform?.address || process.env.THRONOS_PLATFORM_WALLET,
    };
  } catch (err) {
    console.error(`❌ Failed to parse deployment.json: ${(err as Error).message}`);
    return {};
  }
}

/**
 * Generate .env.thronos-bridge for roadway-assistant.
 */
function generateRoadwayEnv(config: ThronosConfig): string {
  return `# 🔗 Thronos Bridge Configuration (Auto-synced)
# Generated: ${new Date().toISOString()}
# Source: ${path.join(THRONOS_ROOT, '.env')} and deployment.json

# ─── Thronos Node URLs ───────────────────────────────────────────────────────
THRONOS_NODE_URL="${config.nodeUrl}"
THRONOS_GATEWAY_URL="https://thronoschain.vercel.app"

# ─── EVM Configuration ───────────────────────────────────────────────────────
THRONOS_EVM_RPC_URL="${config.evmRpcUrl}"
THRONOS_CHAIN_ID="${config.chainId}"
NEXT_PUBLIC_THRONOS_EVM_RPC_URL="${config.evmRpcUrl}"
NEXT_PUBLIC_THRONOS_CHAIN_ID="${config.chainId}"
NEXT_PUBLIC_THRONOS_CHAIN_NAME="Thronos EVM"
NEXT_PUBLIC_THRONOS_NATIVE_SYMBOL="THR"
NEXT_PUBLIC_THRONOSCHAIN_RPC="${config.evmRpcUrl}"

# ─── Smart Contracts ────────────────────────────────────────────────────────
THRONOS_ESCROW_CONTRACT="${config.escrowContract}"
THRONOS_SERVICEBOOK_CONTRACT="${config.servicebookContract}"
THRONOS_REWARD_VAULT_CONTRACT="${config.rewardVaultContract}"
THRONOS_REWARD_TOKEN_ADDRESS="${config.rewardTokenAddress}"

ESCROW_CONTRACT_ADDRESS="${config.escrowContract}"
SERVICE_BOOK_CONTRACT_ADDRESS="${config.servicebookContract}"
REWARD_TOKEN_ADDRESS="${config.rewardTokenAddress}"

# ─── Platform Wallet ────────────────────────────────────────────────────────
THRONOS_PLATFORM_WALLET="${config.platformWallet}"

# ─── Private Keys (🔐 KEEP SECURE - never commit to git) ──────────────────────
# Add these manually to Railway Variables or .env.local
THRONOS_DEPLOYER_PRIVATE_KEY="${config.deployerKey || '0x...'}"
THRONOS_PLATFORM_PRIVATE_KEY="${config.platformKey || '0x...'}"

# ─── Attestation ────────────────────────────────────────────────────────────
THRONOS_ATTESTATION_ENABLED="true"
THRONOS_ATTESTATION_MODE="sha256-node"
THRONOS_ATTESTATION_ENDPOINT="https://thrchain.up.railway.app/api/commerce/attest"
THRONOS_ATTESTATION_API_KEY="${config.attestationApiKey || 'generate-with-openssl-rand-hex-32'}"
`;
}

/**
 * Main sync function.
 */
async function syncThronosEnv() {
  console.log('🔗 Syncing Thronos environment to roadway-assistant...\n');

  // Step 1: Read Thronos config
  console.log('📖 Reading Thronos .env...');
  const envConfig = readThronosEnv();
  console.log(`   ✅ Node URL: ${envConfig.nodeUrl}`);
  console.log(`   ✅ Chain ID: ${envConfig.chainId}`);
  console.log(`   ✅ EVM RPC: ${envConfig.evmRpcUrl}\n`);

  // Step 2: Read deployment output
  console.log('📋 Reading Thronos deployment output...');
  const deployConfig = readDeploymentOutput();
  if (deployConfig.escrowContract) {
    console.log(`   ✅ Escrow: ${deployConfig.escrowContract}`);
    console.log(`   ✅ ServiceBook: ${deployConfig.servicebookContract}`);
    console.log(`   ✅ RewardVault: ${deployConfig.rewardVaultContract}`);
    console.log(`   ✅ RewardToken: ${deployConfig.rewardTokenAddress}\n`);
  } else {
    console.warn('   ⚠️  No deployment output found (optional)\n');
  }

  // Step 3: Merge configs
  const config: ThronosConfig = {
    ...envConfig,
    ...deployConfig,
  } as ThronosConfig;

  // Step 4: Generate .env.thronos-bridge
  const envContent = generateRoadwayEnv(config);
  const envPath = path.join(ROADWAY_ROOT, '.env.thronos-bridge');
  fs.writeFileSync(envPath, envContent);
  console.log(`✨ Generated: ${envPath}\n`);

  // Step 5: Instructions
  console.log('📝 Next steps:');
  console.log('   1. Review the generated .env.thronos-bridge');
  console.log('   2. For Railway deployment, set these variables in Railway dashboard:');
  console.log('      - THRONOS_DEPLOYER_PRIVATE_KEY');
  console.log('      - THRONOS_PLATFORM_PRIVATE_KEY');
  console.log('      - THRONOS_ATTESTATION_API_KEY (generate: openssl rand -hex 32)');
  console.log('   3. Then commit and deploy\n');

  console.log('🚀 Ready! The roadway-assistant is now linked to your Thronos deployment.');
}

syncThronosEnv().catch(err => {
  console.error('❌ Sync failed:', err.message);
  process.exit(1);
});
